// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20231010131356_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "Vw",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "Porsche",
                            Name = "Dr. Ing. h. c. F. Porsche AG"
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "Toyota",
                            Name = "Toyota Motor Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "Hyundai",
                            Name = "Hyundai Motor Company"
                        });
                });

            modelBuilder.Entity("DAL.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleMakeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "Golf III",
                            Name = "Golf Mk3",
                            VehicleMakeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "924",
                            VehicleMakeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Celica",
                            VehicleMakeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "RX-7",
                            VehicleMakeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "i30 N",
                            VehicleMakeId = 5
                        });
                });

            modelBuilder.Entity("DAL.VehicleModel", b =>
                {
                    b.HasOne("DAL.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });
#pragma warning restore 612, 618
        }
    }
}
